/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuickNavigation.java
 *
 * Created on Apr 20, 2010, 4:01:14 PM
 */

package kkckkc.jsourcepad.ui.dialog.navigation;

import java.awt.Dialog.ModalityType;

import javax.annotation.PostConstruct;
import javax.swing.JDialog;
import javax.swing.JLabel;

import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author magnus
 */
public class QuickNavigationDialogViewImpl extends javax.swing.JDialog implements QuickNavigationDialogView {

	private java.awt.Frame parent;

	/** Creates new form QuickNavigation */
	@Autowired
    public QuickNavigationDialogViewImpl(java.awt.Frame frame) {
    	super(frame);
    	this.parent = frame;

    	setLocationRelativeTo(parent);
        initComponents();
    }
	
    public JDialog getJDialog() {
        return this;
    }
    
    public javax.swing.JTextField getTextField() {
	    return textField;
    }
    
    public javax.swing.JList getResult() {
	    return result;
    }
    
    public JLabel getPath() {
        return path;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JList();
        path = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        result.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(result);

        path.setText("Path:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(path, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(path)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel path;
    private javax.swing.JList result;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables

}
