/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FindDialogImpl.java
 *
 * Created on 2010-aug-24, 21:44:53
 */

package kkckkc.jsourcepad.ui.dialog.find;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author kkckkc
 */
public class FindDialogViewImpl extends javax.swing.JDialog implements FindDialogView {

    /** Creates new form FindDialogImpl */
	@Autowired
    public FindDialogViewImpl(java.awt.Frame parent) {
        super(parent);
        setTitle("Find");

       	setLocationRelativeTo(parent);
        initComponents();
    }

    @Override
    public JDialog getJDialog() {
        return this;
    }

    public JComboBox getFindField() {
        return findField;
    }

    public JCheckBox getIsCaseSensitive() {
        return isCaseSensitive;
    }

    public JCheckBox getIsRegularExpression() {
        return isRegularExpression;
    }

    public JCheckBox getIsWrapAround() {
        return isWrapAround;
    }

    public JButton getNext() {
        return next;
    }

    public JButton getPrevious() {
        return previous;
    }

    public JButton getReplace() {
        return replace;
    }

    public JButton getReplaceAll() {
        return replaceAll;
    }

    public JComboBox getReplaceField() {
        return replaceField;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findLabel = new javax.swing.JLabel();
        replaceLabel = new javax.swing.JLabel();
        isRegularExpression = new javax.swing.JCheckBox();
        isCaseSensitive = new javax.swing.JCheckBox();
        isWrapAround = new javax.swing.JCheckBox();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        replace = new javax.swing.JButton();
        replaceAll = new javax.swing.JButton();
        findField = new javax.swing.JComboBox();
        replaceField = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        findLabel.setText("Find:");

        replaceLabel.setText("Replace:");

        isRegularExpression.setText("Regular Expression");

        isCaseSensitive.setText("Case Sensitive");

        isWrapAround.setText("Wrap Around");

        next.setMnemonic('N');
        next.setText("Next");

        previous.setMnemonic('P');
        previous.setText("Previous");

        replace.setText("Replace");
        replace.setEnabled(false);

        replaceAll.setText("Replace All");

        findField.setEditable(true);

        replaceField.setEditable(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, findLabel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, replaceLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(replace)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(replaceAll)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 126, Short.MAX_VALUE)
                        .add(previous)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(next))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(isRegularExpression)
                            .add(isCaseSensitive))
                        .add(18, 18, 18)
                        .add(isWrapAround))
                    .add(findField, 0, 509, Short.MAX_VALUE)
                    .add(replaceField, 0, 509, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(findLabel)
                    .add(findField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(replaceLabel)
                    .add(replaceField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(isRegularExpression)
                    .add(isWrapAround))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(isCaseSensitive)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(replace)
                    .add(replaceAll)
                    .add(next)
                    .add(previous))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox findField;
    private javax.swing.JLabel findLabel;
    private javax.swing.JCheckBox isCaseSensitive;
    private javax.swing.JCheckBox isRegularExpression;
    private javax.swing.JCheckBox isWrapAround;
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    private javax.swing.JButton replace;
    private javax.swing.JButton replaceAll;
    private javax.swing.JComboBox replaceField;
    private javax.swing.JLabel replaceLabel;
    // End of variables declaration//GEN-END:variables


}
